trading:
  segment: EQUITY
  exchange: NSE
  stock_name: BANKNIFTY-Aug2026-31000-CE
  security_id: "35564"
  quantity: 1
  product_type: INTRADAY
  transaction_type: BUY
  order_type: LIMIT
  limit_price: 1890.50
  validity: DAY
  expiry: "2026-07-14 14:00"
  strike: 25000
  option_type: CE

risk:
  target_percent: 2
  stoploss_percent: 1
  trailing_sl: false

cloud:
  log_level: INFO
  dry_run: false
  console_log: true
  auto_place_order: true
